In [9]:
import pandas as pd

In [10]:
existing_data = "../data/sensor1.csv"
new_data = "../data/new_data.csv" #RENAME NEW CSV AS new_data

In [11]:
df1 = pd.read_csv(existing_data)
df1 = df1.dropna()
df1["Time"] = pd.to_datetime(df1["Time"])

In [12]:
df2 = pd.read_csv(new_data)
df2 = df2.dropna()
df2["Time"] = pd.to_datetime(df2["Time"])

In [13]:
result = pd.concat([df1, df2], ignore_index=True).drop_duplicates(subset='Time', keep='first')

In [14]:
result = result.sort_values(by='Time', ascending=True).reset_index(drop=True)

In [15]:
result

,Time,CO2,Humidity,PM10,PM2.5,Temperature,TVOC
0,2024-02-12 22:00:00,456 ppm,79 %H,5.60 μg/m³,5.60 μg/m³,24 °C,0.642 ppm
1,2024-02-12 23:00:00,456 ppm,79 %H,5.25 μg/m³,5.13 μg/m³,24.1 °C,0.711 ppm
2,2024-02-13 00:00:00,456 ppm,79 %H,6 μg/m³,5.89 μg/m³,24.2 °C,0.744 ppm
3,2024-02-13 01:00:00,450 ppm,79 %H,6.44 μg/m³,6.33 μg/m³,24.2 °C,0.759 ppm
4,2024-02-13 02:00:00,447 ppm,79 %H,6.25 μg/m³,5.88 μg/m³,24.3 °C,0.775 ppm
...,...,...,...,...,...,...,...
950,2024-03-23 14:00:00,475 ppm,77.3 %H,23.3 μg/m³,22.2 μg/m³,23.2 °C,0.333 ppm
951,2024-03-23 15:00:00,481 ppm,76.8 %H,22.3 μg/m³,21.7 μg/m³,23.2 °C,0.308 ppm
952,2024-03-23 16:00:00,487 ppm,77.1 %H,23.7 μg/m³,23 μg/m³,23.2 °C,0.387 ppm
953,2024-03-23 17:00:00,499 ppm,77.2 %H,24.8 μg/m³,22.7 μg/m³,23.1 °C,0.343 ppm
954,2024-03-23 18:00:00,505 ppm,77.5 %H,28 μg/m³,26 μg/m³,23.1 °C,0.260 ppm

In [16]:
result.to_csv('../data/sensor1.csv', index=False)